### ISSUE TITLE
API Test

### ISSUE THREAD

**Issue by OnlyNyZe** [Saibe1111/WeRekt#3]
First here's the link of the API Documentation : [https://api-docs.igdb.com/#about](https://api-docs.igdb.com/#about)

**Comment by OnlyNyZe** [comment]
To retrieve a game cover, we need to build our own url like this : https://images.igdb.com/igdb/image/upload/t_{image_size}/{cover_id}.jpg

**Comment by HocusPocusCitrus** [comment]
Example of data sent:
```
fields name, id, cover.image_id, platforms.name, multiplayer_modes.onlinecoopmax, multiplayer_modes.onlinemax;
where multiplayer_modes.onlinecoopmax != 0 & multiplayer_modes.onlinemax != 0 & name ~ "a"*;
limit 10;
```

It retrieves the information specified in "fields" for the first 10 games that start with an "a" or "A" and that have an online multiplayer mode.

We should limit the max number of players with max(multiplayer_modes.onlinecoopmax, multiplayer_modes.onlinemax).
